import { Inter } from "next/font/google";
import Sidebar from "../components/dashboard/sidebar/Sidebar";
import Navbar from "../components/dashboard/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <div className="flex flex-col md:flex-row  bg-[#151C2D] min-h-screen w-full gap-5">
                <Sidebar />
                <div className="content w-full">
                    <Navbar />
                    {children}
                </div>
            </div>
        </>
    );
}
